---
- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - otc-golangci-lint
        - golang-make-test
        - golang-make-vet
    gate:
      jobs:
        - otc-golangci-lint
        - golang-make-test
        - golang-make-vet
